name: CMake-Release

on:
  release:
    types: [prereleased]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # The number of days to retain artifacts
  RETENTION_DAYS: 30

jobs:

  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake MSVC
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build MSVC
        run: |
          cmake --build build --target GenerateEPKS
          cmake --build build --config ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v4
        with:
          name: edge-classic
          path: |
            autoload
            docs
            soundfont
            edge-classic.exe
            *.epk
            CHANGELOG.md
          retention-days: ${{env.RETENTION_DAYS}} 