// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id: 64e802bf19aa17bd7562c5c86f2a3795c8a7da69 $
//
// Copyright (C) 1993-1996 by id Software, Inc.
// Copyright (C) 2006-2020 by The Odamex Team.
// Copyright (C) 2024 by The MUD Team.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// DESCRIPTION:
//		Default Config File.
//		1/5/12: JSON File Functions
//
//-----------------------------------------------------------------------------

#include "m_misc.h"

#include "c_dispatch.h"
#include "i_system.h"
#include "m_argv.h"
#include "m_fileio.h"
#include "mud_includes.h"
#include "sv_main.h"
#include "sv_master.h"
#include "z_zone.h"

// Used to identify the version of the game that saved
// a config file to compensate for new features that get
// put into newer configfiles.
static CVAR(configver, CONFIGVERSIONSTR, "", CVARTYPE_STRING, CVAR_ARCHIVE | CVAR_NOENABLEDISABLE)

// [RH] Don't write a config file if M_LoadDefaults hasn't been called.
bool DefaultsLoaded;

/**
 * Save a configuration file.
 *
 * @author Randy Heit
 * @param Optional: The filename to save the current configuration to.
 */
void STACK_ARGS M_SaveDefaults()
{
    PHYSFS_File *f;

    if (!DefaultsLoaded)
        return;

    // Make sure the user hasn't changed configver
    configver.Set(CONFIGVERSIONSTR);

    if ((f = PHYSFS_openWrite("mud-server.cfg")))
    {
        std::string str = StrFormat("// Generated by MUD Server " DOTVERSIONSTR "\n\n");
        str.append("// --- Console variables ---\n\n");
        PHYSFS_writeBytes(f, str.data(), str.size());

        // Archive all cvars marked as CVAR_ARCHIVE
        cvar_t::C_ArchiveCVars(f);

        // Archive all aliases
        str = "\n// --- Aliases ---\n\n";
        PHYSFS_writeBytes(f, str.data(), str.size());
        DConsoleAlias::C_ArchiveAliases(f);

        PHYSFS_close(f);

        Printf(PRINT_HIGH, "Configuration saved to mud-server.cfg.\n");
    }
}

BEGIN_COMMAND(savecfg)
{
    M_SaveDefaults();
}
END_COMMAND(savecfg)

extern int32_t cvar_defflags;
EXTERN_CVAR(dimamount)

/**
 * Load a configuration file from the default configuration file.
 *
 * @author Randy Heit
 */
void M_LoadDefaults(void)
{
    std::string cmd = "exec " + C_QuoteString("mud-server.cfg");

    cvar_defflags = CVAR_ARCHIVE;
    AddCommandString(cmd.c_str());
    cvar_defflags = 0;

    if (configver < 118.0f)
    {
        AddCommandString("alias idclev map ");
        AddCommandString("alias changemap map ");
        AddCommandString("alias ? help ");
    }

    DefaultsLoaded = true;
}

// JSON Utility Functions (based on those from EECS)

// Reads a file in JSON format
bool M_ReadJSON(Json::Value &json, const char *filename)
{
    uint8_t        *buffer = NULL;
    std::string  data;
    Json::Reader reader;
    uint64_t        length;

    if (!(M_FileExists(filename)))
        return false;

    length = M_ReadFile(filename, &buffer);
    if (length > 0 && buffer)
    {
        const char *start = reinterpret_cast<const char *>(buffer);
        const char *end   = reinterpret_cast<const char *>(&buffer[length]);

        bool res = reader.parse(start, end, json);

        Z_Free(buffer);

        if (res == false)
        {
            Printf(PRINT_HIGH, "M_ReadJSONFromFile: Error parsing JSON: %s.\n",
                   reader.getFormattedErrorMessages().c_str());
            return false;
        }

        return true;
    }

    return false;
}

// Writes a file in JSON format.  Third param is true if the output
// should be pretty-printed.
bool M_WriteJSON(const char *filename, Json::Value &value, bool styled)
{
    std::string        out_string;
    Json::FastWriter   fast_writer;
    Json::StyledWriter styled_writer;

    PHYSFS_File *json_out = PHYSFS_openWrite(filename);

    if (json_out == NULL)
        return false;

    if (styled)
    {
        out_string = styled_writer.write(value);
    }
    else
    {
        out_string = fast_writer.write(value);
    }

    int32_t written = PHYSFS_writeBytes(json_out, out_string.data(), out_string.size());

    PHYSFS_close(json_out);

    if (written != out_string.size())
        return false;

    return true;
}

VERSION_CONTROL(m_misc_cpp, "$Id: 64e802bf19aa17bd7562c5c86f2a3795c8a7da69 $")
